# Generated by Django 3.1.7 on 2023-04-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_program', models.CharField(blank=True, max_length=40)),
                ('registration_number', models.IntegerField(blank=True)),
                ('id_number_1', models.FloatField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=10)),
                ('student_semester', models.IntegerField(blank=True)),
                ('latest_year', models.IntegerField(blank=True)),
                ('id_gunet', models.CharField(max_length=30)),
                ('latest_period', models.CharField(max_length=15)),
                ('year_of_enrolment', models.IntegerField(blank=True)),
                ('registration_period', models.CharField(max_length=20)),
                ('way_of_enrolment', models.CharField(max_length=100)),
                ('student_category', models.CharField(max_length=50)),
                ('free_of_tuition', models.CharField(max_length=10)),
                ('active', models.CharField(max_length=10)),
                ('web_active', models.CharField(max_length=10)),
                ('exemption_from_prerequisites', models.CharField(max_length=10)),
                ('part_time', models.CharField(max_length=10)),
                ('current_status', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=20)),
                ('amka', models.CharField(max_length=60)),
                ('tin', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=105)),
                ('name_in_english', models.CharField(max_length=100)),
                ('last_name_in_english', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_Name', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('id_number_2', models.CharField(max_length=255)),
                ('type_of_id', models.CharField(max_length=50)),
                ('rollback_year', models.CharField(max_length=10)),
                ('date_of_registration', models.CharField(max_length=20)),
                ('department_registration', models.CharField(max_length=200)),
                ('code_of_department', models.IntegerField(blank=True)),
            ],
        ),
    ]
