# Generated by Django 3.1.7 on 2023-04-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230418_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_of_academic_year', models.CharField(max_length=40)),
                ('student_class', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=100)),
                ('registration_number', models.IntegerField(blank=True, null=True)),
                ('subject_code', models.CharField(max_length=40)),
                ('grade', models.CharField(max_length=40)),
                ('exam_period', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=40)),
                ('thesis', models.CharField(max_length=10)),
                ('internship', models.CharField(max_length=10)),
                ('ects', models.FloatField(default=True, null=True)),
                ('ps', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=40)),
                ('date1', models.CharField(max_length=40)),
                ('modified_by', models.CharField(max_length=40)),
                ('date2', models.CharField(max_length=40)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.students')),
            ],
        ),
    ]
