# Generated by Django 3.1.7 on 2023-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studentgrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrades',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
    ]
