# Generated by Django 5.0a1 on 2023-11-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_studentgrades_id_alter_students_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
