# Generated by Django 5.0a1 on 2023-11-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_students_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentgrades',
            table='Student Subjects & Grades',
        ),
        migrations.AlterModelTable(
            name='students',
            table='Students',
        ),
    ]
