# Generated by Django 5.0a1 on 2023-11-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_studentgrades_table_alter_students_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentgrades',
            table=None,
        ),
        migrations.AlterModelTable(
            name='students',
            table=None,
        ),
    ]
